### ISSUE TITLE
Release 0.0.3

### ISSUE THREAD

**Issue by vorburger** [akhildevelops/devcontainer-features#9]
@akhildevelops actually in order to be able to use #8 for #7 you would need to tag and release a v0.0.3 of this project to `ghcr.io`, no?

In https://github.com/google/android-fhir/blob/c0414d2e3721eeccb1a9d476689dae457aa0b793/.devcontainer/devcontainer.json#L10 we're using:

    "ghcr.io/akhildevelops/devcontainer-features/android-cli:0": {},

and in the `creation.log` (from Ctrl-P _Codespaces: View Creation Log_ I'm still seeing:

```
#15 0.510 Feature       : Android SDK Platform Tools
2024-07-12 12:41:09.042Z: #15 0.510 Description   : Provides Android Tools
#15 0.510 Id            : ghcr.io/akhildevelops/devcontainer-features/android-cli
2024-07-12 12:41:09.270Z: #15 0.510 Version       : 0.0.2
```

and the `chown` from my PR is (obviously) not running.

Would you be willing to release 0.0.3 ?

**Comment by vorburger** [comment]
@akhildevelops any chance you would be willing to create a 0.0.3 release?

**Comment by akhildevelops** [comment]
Hi @vorburger, released as 0.0.3, lemme know if it fixed the issue

**Comment by vorburger** [comment]
@akhildevelops Thank You!

**Comment by akhildevelops** [comment]
Closing it
